# Permalinks
permalink:           pretty

# Setup
title:               Haskell Guide
tagline:             For DSTIL projects
description:         'Style and library guides for <a href="https://www.haskell.org">Haskell</a> by <a href="https://github.com/dstil">DSTIL</a>.'
url:                 http://dstil.github.io/haskell-guide/
baseurl:             /haskell-guide
paginate:            5
gems:                [jekyll-paginate]

# Custom vars
github:
  repo:              https://github.com/dstil/haskell-guide
